
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author utilisateur
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    
   Question [] QC =new Question[50]; 
    /**
     * Creates new form FenetreQuiz
     */
    private int indexQuestionCourante = 0;
    
    public FenetreQuiz() {
        initComponents();
        Question QC1 = new Question("le chat de Schrodinger est-il mort","oui","non","peut-être","le chat sait",4);
        Question QC2 = new Question("le chat de Schrodinger est-il mort","oui","non","peut-être","le chat sait",4);
        Question QC3 = new Question("le chat de Schrodinger est-il mort","oui","non","peut-être","le chat sait",4);
        Question QC4 = new Question("le chat de Schrodinger est-il mort","oui","non","peut-être","le chat sait",4);
       
        
        QC[0]=QC1;
                QC[1]=QC2;
        QC[2]=QC3;
        QC[3]=QC4;
afficherQuestionCourante();
    }
    
    private void afficherQuestionCourante(){
    Question q =QC[indexQuestionCourante];
    Questions.setText(q.getIntitule());
    Bouton1.setText(q.getProposition1());
    Bouton2.setText(q.getProposition2());
    Bouton3.setText(q.getProposition3());
    Bouton4.setText(q.getProposition4());
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Questions = new javax.swing.JLabel();
        Bouton1 = new javax.swing.JButton();
        Bouton2 = new javax.swing.JButton();
        Bouton3 = new javax.swing.JButton();
        Bouton4 = new javax.swing.JButton();
        Suivant = new javax.swing.JButton();
        Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Questions.setText("jLabel1");
        getContentPane().add(Questions, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Bouton1.setText("jButton1");
        Bouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton1ActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        Bouton2.setText("jButton2");
        Bouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        Bouton3.setText("jButton3");
        getContentPane().add(Bouton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        Bouton4.setText("jButton4");
        getContentPane().add(Bouton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        Suivant.setText("jButton1");
        getContentPane().add(Suivant, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        Score.setText("jLabel1");
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton1ActionPerformed
         Question q =QC[indexQuestionCourante];
         if (q.getIndexBonneReponse() == 1) {
             Score.setText("OK");
         }
         else{
             Score.setText("pas bon");
         }
           // TODO add your handling code here:
    }//GEN-LAST:event_Bouton1ActionPerformed

    private void Bouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton2ActionPerformed
        Question q =QC[indexQuestionCourante];
         if (q.getIndexBonneReponse() == 2) {
             Score.setText("OK");
         }
         else{
             Score.setText("pas bon");
         }        // TODO add your handling code here:
    }//GEN-LAST:event_Bouton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton1;
    private javax.swing.JButton Bouton2;
    private javax.swing.JButton Bouton3;
    private javax.swing.JButton Bouton4;
    private javax.swing.JLabel Questions;
    private javax.swing.JLabel Score;
    private javax.swing.JButton Suivant;
    // End of variables declaration//GEN-END:variables
}
