/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_biourge;

/**
 *
 * @author utilisateur
 */
public class Interface_Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface_Menu.class.getName());

    /**
     * Creates new form Interface_Menu
     */
    public Interface_Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_titre_jeu = new javax.swing.JLabel();
        Bouton_Jouer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_titre_jeu.setFont(new java.awt.Font("Maiandra GD", 2, 48)); // NOI18N
        texte_titre_jeu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_titre_jeu.setText("Cadenas");
        getContentPane().add(texte_titre_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 59));

        Bouton_Jouer.setText("Jouer");
        Bouton_Jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JouerActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_JouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JouerActionPerformed
    InterfaceCode i = new InterfaceCode();
    i.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Bouton_JouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface_Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_Jouer;
    private javax.swing.JLabel texte_titre_jeu;
    // End of variables declaration//GEN-END:variables
}
