/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_cadenas_biourge;

/**
 *
 * @author utilisateur
 */
public class InterfaceCode extends javax.swing.JFrame {

    private Cadenas partie;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceCode.class.getName());

    /**
     * Creates new form InterfaceCode
     */
    public InterfaceCode() {

        initComponents();
        texte_résultat.setText("");
        texte_chiffre_0.setText("0");
        partie = new Cadenas();
        partie.Combinaison();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffres_2 = new javax.swing.JButton();
        down_chiffres_3 = new javax.swing.JButton();
        down_chiffres_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        bouton_recommencer = new javax.swing.JButton();
        texte_résultat = new javax.swing.JLabel();
        texte_tentatives_nb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouver le bon code en moins de 5 tentatives!");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        texte_chiffre_0.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_0.setText("0");
        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        texte_chiffre_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 50, 60));

        texte_chiffre_1.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_1.setText("0");
        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        texte_chiffre_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, -1));

        texte_chiffre_2.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_2.setText("0");
        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, -1));

        texte_chiffre_3.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_3.setText("0");
        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 50, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nombres de chiffres exacts :");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        texte_lbl_nb_chiffres_haut.setText("Nombres de chiffres trop haut :");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 10, -1));

        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 160, -1));

        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        texte_score.setText("Tentatives");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, -1));

        texte_tentatives.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        texte_tentatives.setText("   sur 5");
        texte_tentatives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 80, 60));

        up_chiffre_1.setText("     /\\     ");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        up_chiffre_2.setText("     /\\     ");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        up_chiffre_3.setText("     /\\     ");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        up_chiffre_4.setText("     /\\     ");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        down_chiffre_1.setText("     \\/     ");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        down_chiffres_2.setText("     \\/     ");
        down_chiffres_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffres_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffres_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        down_chiffres_3.setText("     \\/     ");
        down_chiffres_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffres_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffres_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        down_chiffres_4.setText("     \\/     ");
        down_chiffres_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffres_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffres_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 93, 90, 30));

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        texte_résultat.setText("jLabel1");
        getContentPane().add(texte_résultat, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 280, 80, -1));

        texte_tentatives_nb.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        texte_tentatives_nb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_tentatives_nb.setText("0");
        getContentPane().add(texte_tentatives_nb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 20, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        String Texte_Début_0;
        int Valeur_Début_0;
        String Texte_Fin_0;
        int Valeur_Fin_0;
        boolean up_0 = true;
        Texte_Début_0 = texte_chiffre_0.getText();
        Valeur_Début_0 = Integer.parseInt(Texte_Début_0); // j'utilise Integer.parseInt qui est classe.methode() qui prend en entré une chaines de caractère et qui renvoie un int (.parseInt est utilisé car je vais faire des calcule avec la valeur obtenue dans ma classe cadenas). 
        Valeur_Fin_0 = partie.mise_a_jour(Valeur_Début_0, up_0);
        Texte_Fin_0 = Valeur_Fin_0 + "";
        texte_chiffre_0.setText(Texte_Fin_0);

    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffres_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffres_2ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_1;
        int Valeur_Début_1;
        String Texte_Fin_1;
        int Valeur_Fin_1;
        boolean down_1 = false;
        Texte_Début_1 = texte_chiffre_1.getText();
        Valeur_Début_1 = Integer.parseInt(Texte_Début_1);
        Valeur_Fin_1 = partie.mise_a_jour(Valeur_Début_1, down_1);
        Texte_Fin_1 = Valeur_Fin_1 + "";
        texte_chiffre_1.setText(Texte_Fin_1);
    }//GEN-LAST:event_down_chiffres_2ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
        int[] tab_a_envoyer = new int[4];
        int[] tab_reçu = new int[4];
        int tentative;
        tentative = Integer.parseInt(texte_tentatives_nb.getText());

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_bas.setText("0"); // réinisialisation de l'aide
        texte_nb_chiffres_haut.setText("0");
        tab_a_envoyer[0] = Integer.parseInt(texte_chiffre_0.getText());
        tab_a_envoyer[1] = Integer.parseInt(texte_chiffre_1.getText());
        tab_a_envoyer[2] = Integer.parseInt(texte_chiffre_2.getText()); //combinaison proposer par le joueur et envoyer pour vérification
        tab_a_envoyer[3] = Integer.parseInt(texte_chiffre_3.getText());
        tab_reçu = partie.Tester(tab_a_envoyer);

        if (tab_reçu[3] == 1) {
            tentative += 1;
            texte_tentatives_nb.setText(tentative + "");
            bouton_tester.setEnabled(false);
            up_chiffre_1.setEnabled(false);
            up_chiffre_2.setEnabled(false);
            up_chiffre_3.setEnabled(false);
            up_chiffre_4.setEnabled(false);
            down_chiffre_1.setEnabled(false);
            down_chiffres_2.setEnabled(false);
            down_chiffres_3.setEnabled(false);
            down_chiffres_4.setEnabled(false);

            texte_résultat.setText("Victoire");
        } else if (tab_reçu[3] == 0) {
            tentative += 1;
            if (tentative == 5) {
                bouton_tester.setEnabled(false);
                up_chiffre_1.setEnabled(false);
                up_chiffre_2.setEnabled(false);
                up_chiffre_3.setEnabled(false);
                up_chiffre_4.setEnabled(false);
                down_chiffre_1.setEnabled(false);
                down_chiffres_2.setEnabled(false);
                down_chiffres_3.setEnabled(false);
                down_chiffres_4.setEnabled(false);

                texte_résultat.setText("Perdu");
            }
            texte_tentatives_nb.setText(tentative + "");
            texte_nb_chiffres_exacts.setText(tab_reçu[0] + "");
            texte_nb_chiffres_bas.setText(tab_reçu[1] + "");
            texte_nb_chiffres_haut.setText(tab_reçu[2] + "");

        }


    }//GEN-LAST:event_bouton_testerActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_0;
        int Valeur_Début_0;
        String Texte_Fin_0;
        int Valeur_Fin_0;
        boolean down_0 = false;
        Texte_Début_0 = texte_chiffre_0.getText();
        Valeur_Début_0 = Integer.parseInt(Texte_Début_0); // j'utilise Integer.parseInt qui est classe.methode() qui prend en entré une chaines de caractère et qui renvoie un int (.parseInt est utilisé car je vais faire des calcule avec la valeur obtenue dans ma classe cadenas). 
        Valeur_Fin_0 = partie.mise_a_jour(Valeur_Début_0, down_0);
        Texte_Fin_0 = Valeur_Fin_0 + "";
        texte_chiffre_0.setText(Texte_Fin_0);
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_1;
        int Valeur_Début_1;
        String Texte_Fin_1;
        int Valeur_Fin_1;
        boolean up_1 = true;

        Texte_Début_1 = texte_chiffre_1.getText();
        Valeur_Début_1 = Integer.parseInt(Texte_Début_1);
        Valeur_Fin_1 = partie.mise_a_jour(Valeur_Début_1, up_1);
        Texte_Fin_1 = Valeur_Fin_1 + "";

        texte_chiffre_1.setText(Texte_Fin_1);
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffres_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffres_3ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_2;
        int Valeur_Début_2;
        String Texte_Fin_2;
        int Valeur_Fin_2;
        boolean down_2 = false;
        Texte_Début_2 = texte_chiffre_2.getText();
        Valeur_Début_2 = Integer.parseInt(Texte_Début_2);
        Valeur_Fin_2 = partie.mise_a_jour(Valeur_Début_2, down_2);
        Texte_Fin_2 = Valeur_Fin_2 + "";
        texte_chiffre_2.setText(Texte_Fin_2);
    }//GEN-LAST:event_down_chiffres_3ActionPerformed

    private void down_chiffres_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffres_4ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_3;
        int Valeur_Début_3;
        String Texte_Fin_3;
        int Valeur_Fin_3;
        boolean down_3 = false;
        Texte_Début_3 = texte_chiffre_3.getText();
        Valeur_Début_3 = Integer.parseInt(Texte_Début_3);
        Valeur_Fin_3 = partie.mise_a_jour(Valeur_Début_3, down_3);
        Texte_Fin_3 = Valeur_Fin_3 + "";
        texte_chiffre_3.setText(Texte_Fin_3);
    }//GEN-LAST:event_down_chiffres_4ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_2;
        int Valeur_Début_2;
        String Texte_Fin_2;
        int Valeur_Fin_2;
        boolean up_2 = true;

        Texte_Début_2 = texte_chiffre_2.getText();
        Valeur_Début_2 = Integer.parseInt(Texte_Début_2);
        Valeur_Fin_2 = partie.mise_a_jour(Valeur_Début_2, up_2);
        Texte_Fin_2 = Valeur_Fin_2 + "";

        texte_chiffre_2.setText(Texte_Fin_2);
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        // TODO add your handling code here:
        String Texte_Début_3;
        int Valeur_Début_3;
        String Texte_Fin_3;
        int Valeur_Fin_3;
        boolean up_3 = true;

        Texte_Début_3 = texte_chiffre_3.getText();
        Valeur_Début_3 = Integer.parseInt(Texte_Début_3);
        Valeur_Fin_3 = partie.mise_a_jour(Valeur_Début_3, up_3);
        Texte_Fin_3 = Valeur_Fin_3 + "";

        texte_chiffre_3.setText(Texte_Fin_3);
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        // TODO add your handling code here:
        texte_résultat.setText("");
        texte_chiffre_0.setText("0");
        partie = new Cadenas();
        partie.Combinaison();
        bouton_tester.setEnabled(true);
        up_chiffre_1.setEnabled(true);
        up_chiffre_2.setEnabled(true);
        up_chiffre_3.setEnabled(true);
        up_chiffre_4.setEnabled(true);
        down_chiffre_1.setEnabled(true);
        down_chiffres_2.setEnabled(true);
        down_chiffres_3.setEnabled(true);
        down_chiffres_4.setEnabled(true);
        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_bas.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_tentatives_nb.setText("0");
        
        


    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceCode().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffres_2;
    private javax.swing.JButton down_chiffres_3;
    private javax.swing.JButton down_chiffres_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_résultat;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JLabel texte_tentatives_nb;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
