/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_biourge_version_console;

import java.awt.GridLayout;
import java.awt.PopupMenu;
import javax.swing.JPanel;

/**
 *
 * @author utilisateur
 */
public class FenetreTitre extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreTitre.class.getName());
    GrilleDeJeu grille;
    int g_tour = 100;
    /**
     * Creates new form FenetreTitre
     */
    public FenetreTitre() {
        initComponents();//création du titres et du bouton
        javax.swing.JPanel panneauDesign = (javax.swing.JPanel) this.getContentPane(); //manipulation du fond sur lequel est posé le bouton et le texte de plus c'est ce qui se trouve dans init component or ici j'e l'ai supprimé par erreur.
        panneauDesign.setOpaque(false);//rend ce panneaux sur lequel sont posé les composant transparent 
        this.setGlassPane(panneauDesign); //permet la superposition du texte/bouton et de la grille qui change 
    panneauDesign.setVisible(true);
        JPanel PanneauGrilleDécor = new JPanel();
        PanneauGrilleDécor.setLayout(new GridLayout(10, 10));
        this.grille = new GrilleDeJeu(10, 10);
       
        PanneauGrilleDécor.setLayout(new GridLayout(10,10));
        for (int h = 0; h < 10; h++) {
            for (int k = 0; k < 10; k++) {
                CelluleGraphique bouton_decor = new CelluleGraphique(grille.matriceCellules[h][k], 40, 40);
                PanneauGrilleDécor.add(bouton_decor);}}
      this.setContentPane(PanneauGrilleDécor);
      initialiserPartie();
      this.pack();
      this.revalidate();
    }
    
    public void initialiserPartie() {
        this.grille.melangerMatriceAleatoirement(g_tour);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrilleDécor = new javax.swing.JPanel();
        texte_titre = new javax.swing.JLabel();
        btn_jouer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrilleDécor.setOpaque(false);
        PanneauGrilleDécor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_titre.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        texte_titre.setForeground(new java.awt.Color(255, 255, 255));
        texte_titre.setText("Lights off");
        texte_titre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanneauGrilleDécor.add(texte_titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btn_jouer.setText("Jouer");
        btn_jouer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jouerActionPerformed(evt);
            }
        });
        PanneauGrilleDécor.add(btn_jouer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        getContentPane().add(PanneauGrilleDécor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_jouerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jouerActionPerformed
        // TODO add your handling code here:
        FenetrePrincipale f = new FenetrePrincipale() ; 
        f.setVisible(true) ;
    }//GEN-LAST:event_btn_jouerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreTitre().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauGrilleDécor;
    private javax.swing.JButton btn_jouer;
    private javax.swing.JLabel texte_titre;
    // End of variables declaration//GEN-END:variables

    
    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
   
}
